[package]
name = "gtk4-test"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
chronos = "0.0.0"
gtk4 = {version = "0.9.3", features = ["v4_16"]}
gtk4-layer-shell = "0.4.0"
sass-rs = "0.2.2"
tokio = { version = "1.41.0", features = ["full"] }
